In [1]:
import numpy as np

In [11]:
a = np.linspace(0, 7, 8)
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [15]:
a[[True, True, False, False, False, False, False, False]]

array([0., 1.])

In [16]:
a[a % 2 == 0]

array([0., 2., 4., 6.])

In [17]:
a[False]

array([], shape=(0, 8), dtype=float64)

In [22]:
# this returns the boolean mask
bool_mask = a % 2 == 0

In [23]:
# thats why a[bool_mask] (equals a[a % 2 == 0]) works
a[bool_mask]

array([0., 2., 4., 6.])